#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\animation.bof
BOFS = \
	animation_blast_of_fire.bof \
	animation_blind.bof \
	animation_dazzle.bof \
	animation_dement.bof \
	animation_earthquake.bof \
	animation_explosive_frost.bof \
	animation_hold.bof \
	animation_holy_blaze.bof \
	animation_ice_nova.bof \
	animation_lightning.bof \
	animation_purge.bof \
	animation_purify.bof \
	animation_shocking_fury.bof \
	animation_slow.bof \
	animation_splash_of_acid.bof \
	animation_vampiric_drain.bof \
	animation_vertigo.bof
	
!include $(KODDIR)\kod.mak